on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always
  REGISTRY: ghcr.io

jobs:
  cd:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: wasm32-wasip2
          cache-directories: "**/target"
          cache-all-crates: "true"

      - name: Setup wash
        uses: wasmCloud/setup-wash-action@main
        with:
          wash-version: wash-v2.0.0-rc.8

      - name: Fetch WIT dependencies
        run: echo "namespace_registries.wasco-dev = \"wasco.dev\"" | WKG_CONFIG_FILE="/dev/stdin" wash wit fetch

      - name: Build project
        run: cargo build --release --target wasm32-wasip2

      - name: Log in to ghcr
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to ghcr
        run: |
          package_registry_path="${{ env.REGISTRY }}/$(sed -nE 's/package wasco-dev:([a-z-]+)@([0-9]\.[0-9]\.[0-9]);/wasco-dev\/\1:\2/p' wit/world.wit)"
          wash oci push $package_registry_path target/wasm32-wasip2/release/*.wasm
